/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as EstatusRouteImport } from './routes/estatus'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as PedidoRapidoRouteImport } from './routes/pedido-rapido'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as ProductoSkuRouteImport } from './routes/producto.$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatusRoute = EstatusRouteImport.update({
  id: '/estatus',
  path: '/estatus',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRapidoRoute = PedidoRapidoRouteImport.update({
  id: '/pedido-rapido',
  path: '/pedido-rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSkuRoute = ProductoSkuRouteImport.update({
  id: '/producto/$sku',
  path: '/producto/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/estatus': typeof EstatusRoute
  '/inventario': typeof InventarioRoute
  '/logistica': typeof LogisticaRoute
  '/pedido': typeof PedidoRoute
  '/pedido-rapido': typeof PedidoRapidoRoute
  '/soporte': typeof SoporteRoute
  '/producto/$sku': typeof ProductoSkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/estatus': typeof EstatusRoute
  '/inventario': typeof InventarioRoute
  '/logistica': typeof LogisticaRoute
  '/pedido': typeof PedidoRoute
  '/pedido-rapido': typeof PedidoRapidoRoute
  '/soporte': typeof SoporteRoute
  '/producto/$sku': typeof ProductoSkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/estatus': typeof EstatusRoute
  '/inventario': typeof InventarioRoute
  '/logistica': typeof LogisticaRoute
  '/pedido': typeof PedidoRoute
  '/pedido-rapido': typeof PedidoRapidoRoute
  '/soporte': typeof SoporteRoute
  '/producto/$sku': typeof ProductoSkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/estatus'
    | '/inventario'
    | '/logistica'
    | '/pedido'
    | '/pedido-rapido'
    | '/soporte'
    | '/producto/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/estatus'
    | '/inventario'
    | '/logistica'
    | '/pedido'
    | '/pedido-rapido'
    | '/soporte'
    | '/producto/$sku'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/estatus'
    | '/inventario'
    | '/logistica'
    | '/pedido'
    | '/pedido-rapido'
    | '/soporte'
    | '/producto/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  EstatusRoute: typeof EstatusRoute
  InventarioRoute: typeof InventarioRoute
  LogisticaRoute: typeof LogisticaRoute
  PedidoRoute: typeof PedidoRoute
  PedidoRapidoRoute: typeof PedidoRapidoRoute
  SoporteRoute: typeof SoporteRoute
  ProductoSkuRoute: typeof ProductoSkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatus': {
      id: '/estatus'
      path: '/estatus'
      fullPath: '/estatus'
      preLoaderRoute: typeof EstatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-rapido': {
      id: '/pedido-rapido'
      path: '/pedido-rapido'
      fullPath: '/pedido-rapido'
      preLoaderRoute: typeof PedidoRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$sku': {
      id: '/producto/$sku'
      path: '/producto/$sku'
      fullPath: '/producto/$sku'
      preLoaderRoute: typeof ProductoSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  EstatusRoute: EstatusRoute,
  InventarioRoute: InventarioRoute,
  LogisticaRoute: LogisticaRoute,
  PedidoRoute: PedidoRoute,
  PedidoRapidoRoute: PedidoRapidoRoute,
  SoporteRoute: SoporteRoute,
  ProductoSkuRoute: ProductoSkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
